{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <feature_profile_test.TestProfileFeature object at 0x00000229C94A5E50>\n\n    @pytest.mark.bad\n    def test_two(self):\n>       assert False\nE       assert False\n\ntests\\feature_profile_test.py:27: AssertionError"}, "start": 1707755744645, "stop": 1707755744646, "uuid": "1b3a2047-9fa6-44d5-b2bf-4b429cdc176b", "historyId": "0e8b9fd43ab9db5cd07116323b9d06f6", "testCaseId": "0e8b9fd43ab9db5cd07116323b9d06f6", "fullName": "tests.feature_profile_test.TestProfileFeature#test_two", "labels": [{"name": "feature", "value": "Profile Functionality"}, {"name": "tag", "value": "bad"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "feature_profile_test"}, {"name": "subSuite", "value": "TestProfileFeature"}, {"name": "host", "value": "DESKTOP"}, {"name": "thread", "value": "21532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.feature_profile_test"}]}